name: paymentez_mobile
description: A new Flutter module to use the paymentez services for Android and IOS apps.
publish_to: "none"

version: 1.0.1+6

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^4.0.0
  equatable: ^2.0.5
  meta: ^1.1.8
  font_awesome_flutter: ^10.2.1
  flutter_bloc: ^8.1.1
  path_provider: ^2.0.1
  after_layout: ^1.2.0
  crypto: ^3.0.1
  flutter_svg: ^1.1.5
  mask_text_input_formatter: ^2.4.0
  fluro: ^2.0.3
  flutter_kount:
    git:
      url: https://github.com/oaacelasu/flutter_kount
      ref: migrate_to_null_safety
  flutter_card_io_v2:
    git:
      url: https://github.com/oaacelasu/flutter_card_io_v2
      ref: migrate_to_null_safety

  cupertino_icons: ^1.0.5

flutter:
  assets:
    - assets/
    - assets/images/
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.paymentez.paymentez_mobile
    iosBundleIdentifier: com.paymentez.paymentezMobile
